added test
YurySuvalau/Booking_com pull request #1
Opened 2021-02-18 18:30 UTC by YurySuvalau

2021-02-19 08:13 UTC, vchesnakoutest requested changes

2021-02-19 08:13 UTC, vchesnakoutest commented on src/test/java/steps/BookingSteps.java
> +        assertThat($$(By.xpath(String.format("//*[contains(@class,'sr-hotel__name')and contains(text(),'%s')]/ancestor::*[contains(@class,'sr_item_content_slider_wrapper')]//*[@class = 'bui-review-sc
It's better to compare text just for one element in this case (not a collection).
Use assertThat($(By.xpath...............getText()....

2021-02-19 13:03 UTC, YurySuvalau commented on src/test/java/steps/BookingSteps.java
> +        assertThat($$(By.xpath(String.format("//*[contains(@class,'sr-hotel__name')and contains(text(),'%s')]/ancestor::*[contains(@class,'sr_item_content_slider_wrapper')]//*[@class = 'bui-review-sc
fix

2021-02-20 11:22 UTC, vchesnakoutest approved these changes
please merge

2021-02-20 11:33 UTC, merged